In [31]:
import pandas as pd
import numpy as np
from sklearn import linear_model
 

In [32]:
df = pd.read_csv('homeprices_m.csv')

In [33]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [34]:
df.bedrooms.median()

4.0

In [35]:
median_bedrooms = df.bedrooms.median()

In [36]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [37]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [38]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [39]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [40]:
reg.intercept_

221323.00186540408

In [41]:
reg.predict([[3000, 3, 40]])

array([498408.25158031])

In [44]:
import pickle

In [45]:
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)

In [46]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [50]:
mp.predict([[3000, 3, 40]])

array([498408.25158031])

In [51]:
from sklearn.externals import joblib

In [52]:
joblib.dump(reg, 'model_joblib')

['model_joblib']

In [53]:
joblib.load('model_joblib')

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [54]:
mk = joblib.load('model_joblib')

In [55]:
mk.predict([[3000,3,40]])

array([498408.25158031])

In [56]:
mk.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [58]:
mp.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])